services:
  # 1. قاعدة البيانات (PostgreSQL)
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: my_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_net

  # 2. التطبيق (الباك إند والفرونت إند معاً)
  app:
    build:
      context: .
      target: development # نستخدم مرحلة التطوير هنا
    container_name: node_app_dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://admin:admin123@postgres:5432/my_database
      - JWT_SECRET=your_super_secret_key
    ports:
      - "4000:4000" # منفذ السيرفر
      - "5173:5173" # منفذ الفرونت إند (Vite) للتطوير
      - "5555:5555" # منفذ Prisma Studio
    volumes:
      - .:/app
      - /app/node_modules # حماية لمكتبات الحاوية
      - /app/my-front-end/node_modules # حماية لمكتبات الفرونت إند
    depends_on:
      - postgres
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge