services:
  # خدمة قاعدة البيانات
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: my_database
      # يُفضل إضافة هذا السطر لضمان عدم حدوث مشاكل اتصال في البداية
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - app_netfastify

  # خدمة مشروع النود
  nodefasstify:
    build:
      context: .
      target: production
    image: nodeapp_dev_image
    container_name: node_app_dev
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://admin:admin123@postgres:5432/my_database
      - JWT_SECRET=1234456677
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    networks:
      - app_netfastify


volumes:
  postgres_data:

networks:
  app_netfastify:
    driver: bridge
